version: "3"
services:
    mbp:
        build:
            context: ./mbp_container/
            args:
                branch: externalize_config
        container_name: mbp
        ports:
            - 22
            - 80:8080
        hostname: mbp
        links:
            - mongodb:mongodb
            - mosquitto:mosquitto
            
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        ports:
            - 27017
        hostname: mongodb
        volumes:
            - /data/db
   
    mosquitto:
        image: eclipse-mosquitto:1.6.14
        container_name: mosquitto
        restart: always
        ports:
            - 1883:1883
            - 9001:9001
        hostname: mosquitto
